//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LOAIXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIXE()
        {
            this.CHITIETHOPDONGs = new HashSet<CHITIETHOPDONG>();
            this.XEs = new HashSet<XE>();
        }
        [Display(Name ="Mã Loại Xe")]
        public int MALOAIXE { get; set; }
        [Display(Name = "Tên Loại Xe")]
        public string TENLOAIXE { get; set; }
        [DisplayName("Số Chỗ")]
        public Nullable<int> SOCHO { get; set; }
        [DisplayName("Số Lượng Xe")]
        public Nullable<int> SOLUONGXE { get; set; }
        [DisplayName("Hãng Sản Xuất")]
        public string HANGSANXUAT { get; set; }
        [DisplayName("Hình Ảnh")]
        public string HINHANH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOPDONG> CHITIETHOPDONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XE> XEs { get; set; }
    }
}
