//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.CHITIETDONDATs = new HashSet<CHITIETDONDAT>();
            this.CHITIETTHANHLYHOPDONGs = new HashSet<CHITIETTHANHLYHOPDONG>();
        }
        public int MAXE { get; set; }
        public int MALOAIXE { get; set; }
        public string TENXE { get; set; }
        public string BIENSO { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<int> SONGAYDAT { get; set; }
        public Nullable<int> TIENCOC { get; set; }
        public string TINHTRANG { get; set; }
        public string MOTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDAT> CHITIETDONDATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETTHANHLYHOPDONG> CHITIETTHANHLYHOPDONGs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
    }
}
