//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOPDONG
    {
        public int MACTHOPDONG { get; set; }
        public int MAHOPDONG { get; set; }
        public Nullable<int> MALOAIXE { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> GIA { get; set; }
        public Nullable<System.DateTime> NGAYNHAN { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public string GHICHU { get; set; }
    
        public virtual HOPDONG HOPDONG { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
    }
}
