//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATXE()
        {
            this.CHITIETDONDATs = new HashSet<CHITIETDONDAT>();
        }
    
        public int MADATXE { get; set; }
        public int MAKHACH { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> TIENCOC { get; set; }
        public Nullable<int> TIENTRA { get; set; }
        public int MATRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDAT> CHITIETDONDATs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual TRANGTHAI TRANGTHAI { get; set; }
    }
}
