//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDONDATXE
    {
        public string MaCTDonDatXe { get; set; }
        public string MaDatXe { get; set; }
        public string MaXe { get; set; }
        public string MoTaCT { get; set; }
    
        public virtual DONDATXE DONDATXE { get; set; }
        public virtual XE XE { get; set; }
    }
}
