//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONDATXE()
        {
            this.CHITIETDONDATXEs = new HashSet<CHITIETDONDATXE>();
        }
    
        public string MaDatXe { get; set; }
        public System.DateTime NgayDatXe { get; set; }
        public Nullable<int> TienCoc { get; set; }
        public int TienTra { get; set; }
        public string MaKhach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDATXE> CHITIETDONDATXEs { get; set; }
        public virtual KHACH KHACH { get; set; }
    }
}
