//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.CHITIETDONDATXEs = new HashSet<CHITIETDONDATXE>();
        }
    
        public string MaXe { get; set; }
        public string MaLoaiXe { get; set; }
        public string TenXe { get; set; }
        public string BienSo { get; set; }
        public int DonGia { get; set; }
        public Nullable<int> TienCoc { get; set; }
        public System.DateTime NgayDatXe { get; set; }
        public string MoTa { get; set; }
        public string TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONDATXE> CHITIETDONDATXEs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
    }
}
